name: Deleting development Infra

on:
  workflow_dispatch:

jobs:

  deleting-dev-infra:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.DEV_AWS_REGION }}
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Installation
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.4

    - name: Verify Terraform Installation
      run: terraform --version

    - name: Initialize Terraform
      run: terraform init  --backend-config=development-backend.conf 
      working-directory: ./terraform/


    - name: Apply Terraform Code
      run: terraform destroy -var-file=development.tfvars  -auto-approve 
      working-directory: ./terraform/
